1주차/10814/10814_java_포키.java
1주차/14659/14659_java_포키.java
1주차/17362/17362_java_포키.java
1주차/4796/4796_java_포키.java

안녕하세요! 알고리즘이 거의 처음이라 제 맘대로 냅다 풀어버렸습니다 ^.^
많이 부족하지만 잘 부탁드려요~!

[포키] 1주차 과제 제출

---

.idea/2022-lv3-algorithm-study.iml
.idea/inspectionProfiles/profiles_settings.xml
.idea/misc.xml
.idea/modules.xml
.idea/vcs.xml
.idea/workspace.xml
1주차/10814/10814_python_제로.py
1주차/14659/14659_python_제로.py
1주차/17362/17362_python_제로.py
1주차/4796/4796_python_제로.py

[제로] 1주차 과제 제출

---

1주차/10814/10814_정.py
1주차/14659/14659_정.py
1주차/17362/17362_정.py
1주차/4796/4796_정.py

안녕하세요 관람객입니다.
문제가 재미있어 보여서 풀어보았습니다.
감사합니다.

[정] 1주차 과제 제출

---

1주차/10814/10814_java_라라.java
1주차/14659/14659_java_라라.java
1주차/17362/17362_java_라라.java
1주차/4796/4796_java_라라.java

[라라] 1주차 과제 제출

---

1주차/10814/10814_java_라쿤.java
1주차/14659/14659_java_라쿤.java
1주차/17362/17362_java_라쿤.java
1주차/4796/4796_java_라쿤.java

[라쿤] 1주차 과제 제출

---

1주차/10814/10814_java_연로그.java
1주차/14659/14659_java_연로그.java
1주차/17362/17362_java_연로그.java
1주차/4796/4796_java_연로그.java

코테 문제 푸는게 우테코 코테 이후로 처음인 것 같네요 ㅎ.....
잘 부탁드립니다

[연로그] 1주차 과제 제출

---

1주차/10814/java_10814_루나.java
1주차/14659/java_14659_루나.java
1주차/17362/java_17362_루나.java
1주차/4796/java_4796_루나.java

[루나] 1주차 과제 제출

---

1주차/10814/java_10814_아리.java
1주차/14659/java_14659_아리.java
1주차/17362/java_17362_아리.java
1주차/4796/java_4796_아리.java

[아리] 1주차 과제 제출

---

1주차/10814/10814_java_매트.java
1주차/14659/14659_java_매트.java
1주차/17362/17362_java_매트.java
1주차/4796/4796_java_매트.java

안녕하세요! 매트입니다 😀 이번 리뷰 잘 부탁드립니다! 
[나이순 정렬](https://www.acmicpc.net/problem/10814) 문제에서 출력 조건이 아래와 같은 것을 확인했습니다.
> 첫째 줄부터 총 N개의 줄에 걸쳐 온라인 저지 회원을 나이 순, 나이가 같으면 가입한 순으로 한 줄에 한 명씩 나이와 이름을 공백으로 구분해 출력한다.
회원을 나이 순, 나이가 같으면 가입한 순으로 정렬해야 하는데 age를 기준으로 오름차순 정렬만 진행해도 통과하는 것을 확인했습니다. 이것이 가능한 이유는 java에서 제공하는 기본적인 정렬이 `안정 정렬(Stable Sort)`이기 때문에 가입한 순서를 유지한다고 이해해도 괜찮을까요?

[매트] 1주차 과제 제출

---

1주차/10814/10814_java_디우.java
1주차/14659/14659_java_디우.java
1주차/17362/17362_java_디우.java
1주차/4796/4796_java_디우.java

알고리즘 공부가 처음이라..많이 부족할 것 같습니다..😅
잘부탁드립니다!!😁

[디우] 1주차 과제 제출

---

1주차/10814/10814_java_윤주리.java
1주차/14659/14659_java_윤주리.java
1주차/17362/17362_java_윤주리.java
1주차/4796/4796_java_윤주리.java

안녕하세용 주디입니당 🐇 
가독성은 제로지만 잘부탁드려요 :)

[주디]1주차 과제 제출

---

1주차/10814/java_10814_루키.java
1주차/14659/java_14659_루키.java
1주차/17362/java_17362_루키.java
1주차/4796/java_4796_루키.java

[루키] 1주차 과제 제출

---

1주차/10814/10814_python_아서.py
1주차/14659/14659_python_아서.py
1주차/17362/17362_python_아서.py
1주차/4796/4796_python_아서.py

[아서] 1주차 과제 제출

---

1주차/10814/josh_java_10814.java
1주차/14659/josh_java_14659.java
1주차/17362/josh_java_17362.java
1주차/4796/josh_java_4796.java

[조시] 1주차 과제 제출

---

1주차/10814/kotlin_10814_페퍼.kt
1주차/14659/kotlin_14659_페퍼.kt
1주차/17362/kotlin_17362_페퍼.kt
1주차/4796/kotlin_4796_페퍼.kt

[페퍼] 1주차 과제 제출

---

1주차/10814/10814_Java_짱구.java
1주차/14659/14659_Java_짱구.java
1주차/17362/17362_Java_짱구.java
1주차/4796/4796_Java_짱구.java

[짱구] 1주차 과제 제출

---

1주차/10814/java_10814_유콩.java
1주차/14659/java_14659_유콩.java
1주차/17362/java_17362_유콩.java
1주차/4796/java_4796_유콩.java

[유콩] 1주차 과제 제출

---

1주차/10814/Java_10814_이영환.java
1주차/14659/Java_14659_이영환.java
1주차/17362/Java_17362_이영환.java
1주차/4796/Java_4796_이영환.java

잘 부탁드립니다!🤗
코테 준비 처음 하는데 생각보다 쉽지가 않네요😂

[알렉스] 1주차 과제 제출

---

1주차/10814/10814_Java_레넌.java
1주차/14659/14659_Java_레넌.java
1주차/17362/17362_Java_레넌.java
1주차/4796/4796_Java_레넌.java

[레넌] 1주차 과제 제출 

---

1주차/10814/Kun_10814.java
1주차/14659/Kun_14659.java
1주차/17362/Kun_17362.java
1주차/4796/Kun_4796.java

[쿤] 1주차 과제 제출

---

1주차/10814/Java_10814_토닉.java
1주차/14659/Java_14659_토닉.java
1주차/17362/Java_17362_토닉.java
1주차/4796/Java_4796_토닉.java

@brorae @sc0116
레넌, 짱구 알고리즘 피드백 잘 부탁드립니다 ㅎㅎ

[토닉] 1주차 과제 제출

---

1주차/10814/10814_python_quaritch.py
1주차/14659/14659_python_quaritch.py
1주차/17362/17362_python_quaritch.py
1주차/4796/4796_python_quaritch.py

[쿼리치] 1주차 과제 제출

---

1주차/10814/10814_java_유현호.java
1주차/14659/14659_java_유현호.java
1주차/17362/17362_java_유현호.java
1주차/4796/4796_java_유현호.java

[호호] 1주차 과제 제출

---

2주차/11866/11866_java_라쿤.java
2주차/12789/12789_java_라쿤.java
2주차/2121/2121_java_라쿤.java
2주차/22941/22941_java_라쿤.java
2주차/23827/23827_java_라쿤.java

[라쿤] 2주차 과제 제출

---

2주차/11866/11866_java_렉스.java
2주차/12789/12789_java_렉스.java
2주차/2121/2121_java_렉스.java
2주차/22941/22941_java_렉스.java
2주차/23827/23827_java_렉스.java

**풀이 코드 바로가기**
[(11866) 요세푸스 문제 0](https://github.com/Seongwon97/2022-lv3-algorithm-study/blob/main/2%EC%A3%BC%EC%B0%A8/11866/11866_java_%EB%A0%89%EC%8A%A4.java)
[(12789) 도키도키 간식드리미](https://github.com/Seongwon97/2022-lv3-algorithm-study/blob/main/2%EC%A3%BC%EC%B0%A8/12789/12789_java_%EB%A0%89%EC%8A%A4.java)
[(2121) 넷이 놀기](https://github.com/Seongwon97/2022-lv3-algorithm-study/blob/main/2%EC%A3%BC%EC%B0%A8/2121/2121_java_%EB%A0%89%EC%8A%A4.java)
[(22941) RPG 마스터 오명진](https://github.com/Seongwon97/2022-lv3-algorithm-study/blob/main/2%EC%A3%BC%EC%B0%A8/22941/22941_java_%EB%A0%89%EC%8A%A4.java)
[(23827) 수열](https://github.com/Seongwon97/2022-lv3-algorithm-study/blob/main/2%EC%A3%BC%EC%B0%A8/23827/23827_java_%EB%A0%89%EC%8A%A4.java)

[렉스] 2주차 과제 제출

---

2주차/11866/Java_11866_이영환.java
2주차/12789/Java_12789_이영환.java
2주차/2121/Java_2121_이영환.java
2주차/22941/Java_22941_이영환.java
2주차/23827/Java_23827_이영환.java

[알렉스] 2주차 과제 제출

---

2주차/11866/11866_java_포키.java
2주차/12789/12789_java_포키.java
2주차/2121/2121_java_포키.java
2주차/23827/23827_java_포키.java

아키, 아리 안녕하세요!! 포키입니다. 먼저 세 문제밖에 없는 점 부끄러이 여기며 사과드립니다.
22941, ~23827~(해결) 장렬하게 실패...일이 그렇게 됐네요 😭 
최대한 풀어보고 맞추게 되면 추가해놓겠습니다~! (해당 문제들은 리뷰 안주셔도 제 책임이려니 할게요 ㅠ)

[포키] 2주차 과제 제출

---

1주차/10814/10814_python_yaho.py
1주차/14659/14659_python_yaho.py
1주차/17362/17362_python_yaho.py
1주차/4796/4796_python_yaho.py
2주차/11866/11866_python_yaho.py
2주차/12789/12789_python_yaho.py
2주차/2121/2121_python_yaho.py
2주차/22941/22941_python_yaho.py
2주차/23827/23827_python_yaho.py

[야호] 2주차 과제 제출

---

2주차/11866/11866_정.py
2주차/12789/12789_정.py
2주차/2121/2121_정.py
2주차/22941/22941_정.py
2주차/23827/23827_정.py

아이코! 이번주 문제도 정말 머리가 지끈지끈하네요!
다 풀긴 했는데 솔직히 pypy 안쓰면 메모리 초과되는게 맞는겁니까?

[정] 2주차 과제 제출

---

2주차/11866/11866_python_토르.py
2주차/12789/12789_python_토르.py
2주차/2121/2121_python_토르.py
2주차/22941/22941_python_토르.py
2주차/23827/23827_python_토르.py

안녕하세요~
22941번 [풀다가]( https://www.acmicpc.net/source/45782742) 97퍼에서 틀렸는데 예외 케이스 발견을 못해서 [정답코드](https://cael0.github.io/problem%20solving/NPC_Open_Contest/) 참고 했습니다. 첨에 경우의 수를 자꾸 나누는 것이 맞나 의심을 해서 더 고민을 못했던 것 같네요. 
리뷰 잘 부탁드립니다!

[토르] 2주차 과제 제출

---

2주차/11866/11866_java_매트.java
2주차/12789/12789_java_매트.java
2주차/2121/2121_java_매트.java
2주차/23827/23827_java_매트.java

안녕하세요 페퍼, 루키! 매트 입니다. 😀
시간 부족으로 우선 RPG 마스터 오명진을 제외한 나머지 문제 해결했습니다! 리뷰 잘 부탁 드립니다~

[매트] 2주차 과제 제출

---

2주차/11866/11866_Java_연로그.java
2주차/12789/12789_Java_연로그.java
2주차/2121/2121_Java_연로그.java
2주차/22941/22941_Java_연로그.java
2주차/23827/23827_Java_연로그.java

[연로그] 2주차 과제 제출

---

3주차/11568/11568_java_라쿤.java
3주차/1254/1254_java_라쿤.java
3주차/13702/13702_java_라쿤.java
3주차/17123/17123_java_라쿤.java

[라쿤] 3주차 과제 제출

---

3주차/11568/java_11568_아리.java
3주차/1254/java_1254_아리.java
3주차/13702/java_13702_아리.java
3주차/17123/java_17123_아리.java

3주차도 잘부탁드립니다🙇🏻‍♀️
- [1254 팰린드롬 만들기](https://github.com/ulimy/2022-lv3-algorithm-study/blob/main/3주차/1254/java_1254_아리.java)
- [11568 민균이의 계략](https://github.com/ulimy/2022-lv3-algorithm-study/blob/main/3주차/11568/java_11568_아리.java)
- [13702 이상한 술집](https://github.com/ulimy/2022-lv3-algorithm-study/blob/main/3주차/13702/java_13702_아리.java)
- [17123 배열 놀이](https://github.com/ulimy/2022-lv3-algorithm-study/blob/main/3주차/17123/java_17123_아리.java)

[아리] 3주차 과제 제출 

---

3주차/11568/java_11258_philz.java
3주차/1254/java_1254_philz.java
3주차/17123/java_17123_philz.java

어휴.. 정말 하하하 어렵네요..ㅎㅎ...
코테는 아직 배울점이 많은 것 같아요 ..........ㅎㅎㅎ..........

[필즈] 3주차 과제 제출 

---

1주차/14659/14659_python_후디.py
2주차/11866/11866_java_라라.java
3주차/1254/1254_python_후디.py

하하하... 한문제밖에 풀지 못했네요.
알고리즘 많이 어렵네요 노력하겠습니다 🥲
리뷰 잘 부탁드립니다 여러분..!

[후디] 3주차 과제 제출

---

3주차/11568/11568_java_포키.java
3주차/1254/1254_java_포키.java

유콩, 디우 오랜만이에요~~ 선릉에서 잘 지내고 계신가요 👋
이번주도 2문제밖에 못풀었네욥,, 🙄 
민준이의 계략은 DP 적용이 저는 아직 너무 어려워서 구글링 해보고 제가 이해할 수 있었던 알고리즘을 따라해보았습니다 😭
다들 어케 이런걸 푸시는건가여,, 전 아직 브론즈가 딱인거같아여,,ㅜ

[포키] 3주차 과제 제출

---

3주차/1254/Kun_1254.java

시간이 부족해서 1문제밖에 풀지 못했습니다,, 잘 부탁드립니다

[쿤] 3주차 과제제출

---

3주차/11568/11568_kotlin_페퍼.kt
3주차/1254/1254_kotlin_페퍼.kt

제 팰린드롬 코드는 더티코드 그 자체입니다.. 하지만 코케인 코제로를 믿기에 리팩터링 없이 제출합니다🤪🤪
이상한 술집은 접근을 어떻게 해야할지 아예 감이 안오는데 훌륭하신 리뷰어분들께서 코멘트로 힌트를 주시길 바래봅니다,,🙏
시간이 난다면 배열 놀이도 풀어볼게요🔥
민균이의 계략 덕분에 LIS 알고리즘을 알게되었둥〰️ 이번엔 DP처럼 풀었는데 다음에 이런 유형을 만난다면 이분 탐색으로도 풀어보겠둥〰️
다음주에는 시간관리를 잘해서 꼭 다 풀어보겠둥...😢

[페퍼] 3주차 과제 제출

---

2주차/11866/11866_java_라라.java
3주차/1254/1254_java_라라.java

[라라] 3주차 과제 제출

---

2주차/11866/11866_java_라라.java
3주차/11568/11568_java_매트.java
3주차/1254/1254_java_매트.java
3주차/13702/13702_java_매트.java

안녕하세요 루나, 렉스! 매트입니다 😃
이번에도 바쁜 일주일을 보내느라 3문제 밖에 해결하지 못했네요 ㅜㅠ 폭풍 피드백 부탁드립니다.. 참고사항으로 새롭게 repository를 clone해도 계속해서 2주차 라라가 작성한 문제가 커밋이 안된 채 받아 지더라구요.. 커밋 내역에 함께 파일이 올라갔는데 무시하시고 리뷰 해주시면 감사하겠습니다.

[매트] 3주차 과제 제출

---

3주차/11568/11568_java_렉스.java
3주차/1254/1256_java_렉스.java
3주차/13702/13702_java_렉스.java
3주차/17123/17123_java_렉스.java

남은 한 문제는 내일중에 풀어서 추가 업로드 하겠습니다~

[렉스] 3주차 과제 제출 

---

3주차/11568/11568_java_연로그.java
3주차/1254/1254_java_연로그.java
3주차/13702/13702_java_연로그.java
3주차/17123/17123_java_연로그.java

[연로그] 3주차 과제 제출

---

3주차/11568/11568_python_토르.py
3주차/1254/1254_python_토르.py
3주차/13702/13702_python_토르.py
3주차/17123/17123_python_토르.py

안녕하세요~
배열놀이 문제를 보고 누적합이라는 것까지는 알았는데 하다가 시간이 많이 지체되어서 정답 코드를 보고 풀었네요. 다시 연습해보겠습니다. 감사합니다.

[토르] 3주차 과제 제출

---

3주차/1254/1254_java_hoho.java

안녕하세요 필즈 짱구!!
1문제밖에 풀지 못 했어요ㅜㅜ 잘 부탁드려요~!

[호호] 3주차 과제 제출

---

3주차/11568/11568_python_정.py
3주차/1254/1254_python_정.py
3주차/13702/13702_python_정.py
3주차/17123/17123_python_정.py

[정] 3주차 과제 제출

---

4주차/16198/16198_python_정.py
4주차/18232/18232_python_정.py
4주차/21938/21938_python_정.py

교수님. 유해동물이 깃에 묻어있습니다.
16198번의 경우 처음으로 답을 봐버렸네요.

[정] 4주차 과제 제출

---

4주차/16198/16198_java_연로그.java
4주차/18232/18232_java_연로그.java
4주차/21938/21938_java_연로그.java

과제 제출합니다~
일단 풀이를 본 후에 다음 날에 안보고 푸는 방식으로 도전해보았습니다..
dfs, bfs를 안풀어봐서 접근 방식?을 잘 모르겠더라고요😂💦

[연로그] 4주차 과제 제출

---

3주차/11568/11568_java_라쿤.java
3주차/1254/1254_java_라쿤.java
3주차/13702/13702_java_라쿤.java
3주차/17123/17123_java_라쿤.java
4주차/21938/Java_21938_이영환.java

[알렉스] 4주차 과제 제출

---

4주차/16198/16198_java_포키.java
4주차/21938/21938_java_포키_bfs.java
4주차/21938/21938_java_포키_dfs.java

[포키] 4주차 과제 제출

---

4주차/16198/16198_java_필즈.java
4주차/21938/21938_java_필즈.java

푼 것은 `pass`, 
풀지 못한 것은`fail` 이라고 표기했습니다.. ㅎㅎ
~지금 자정 직전인데 한 문제도 못풀었네요 흐흫ㅠㅠㅠ~

[필즈] 4주차 과제 제출

---

4주차/21938/21938_후디_python.py

RecursionError가 계속 뜨네요 ㅠ,ㅠ 어디서 무한루프에 빠진지 잘 모르겠습니다 🥲

[후디] 4주차 과제 제출

---

4주차/16198/16198_python_토르.py
4주차/18232/18232_python_토르.py
4주차/21938/21938_python_토르.py

[토르] 4주차 과제 제출

---

3주차/11568/11568_java_라쿤.java
3주차/1254/1254_java_라쿤.java
3주차/13702/13702_java_라쿤.java
3주차/17123/17123_java_라쿤.java
4주차/16198/16198_java_매트.java
4주차/18232/18232_java_매트.java
4주차/21938/21938_java_매트.java

안녕하세요 아키, 주디! 매트입니다. 😃
이번엔 3주차 라쿤 파일이 함께 올라가네요.. 무시하고 리뷰 부탁드립니다! 감사합니다🙏

[매트] 4주차 과제 제출

---

.gitignore
1주차/10814/java_10814_유콩.java
1주차/14659/java_14659_유콩.java
1주차/17362/java_17362_유콩.java
1주차/4796/java_4796_유콩.java
2주차/11866/README.md
2주차/11866/java_11866_유콩.java
2주차/12789/README.md
2주차/12789/java_12789_유콩.java
2주차/2121/README.md
2주차/2121/java_2121_유콩.java
2주차/22941/README.md
2주차/23827/README.md
2주차/23827/java_23827_유콩.java
3주차/11568/README.md
3주차/11568/java_11568_유콩.java
3주차/1254/README.md
3주차/1254/java_1254_유콩.java
3주차/13702/README.md
3주차/13702/java_13702_유콩.java
3주차/17123/README.md
3주차/17123/java_17123_유콩.java
4주차/16198/README.md
4주차/16198/java_16198_유콩.java
4주차/18232/README.md
4주차/21938/README.md

한문제밖에 못풀었습니다...
그래도 잘 부탁드립니다..... 😭

[유콩] 4주차 과제 제출

---

3주차/11568/11568_java_라쿤.java
3주차/1254/1254_java_라쿤.java
3주차/13702/13702_java_라쿤.java
3주차/17123/17123_java_라쿤.java
4주차/16198/16198_java_아리.java
4주차/18232/18232_java_아리.java
4주차/21938/21938_java_아리.java

이유는 정말 모르겠으나 rebase를 해도, 지웠다가 다시 클론받아도 라쿤 파일이 커밋 되지 않았다고 뜨네요ㅠㅠㅠ
무시하고 리뷰해주시기를 부탁드립니다!

[아리] 4주차 문제 제출

---

4주차/16198/16198_java_라쿤.java
4주차/18232/18232_java_라쿤.java
4주차/21938/21938_java_라쿤.java

[라쿤] 4주차 문제 제출

---

4주차/16198/16198_java_렉스.java
4주차/18232/18232_java_렉스.java
4주차/21938/21938_java_렉스.java

DFS, BFS가 너무 오랜만이라 16918번은 구글의 도움을 받았습니다..
18232번은 풀긴했지만 엄청 메모리 사용이랑 시간 측면에서 모두 좋지 않은것 같네요😭
리뷰 잘 부탁드립니다.

 [렉스] 4주차 과제 제출

---

4주차/16198/16198_python_제로.py
4주차/18232/18232_python_제로.py
4주차/21938/21938_python_제로.py

[제로] 4주차 과제 제출

---

4주차/16198/16198_java_라쿤.java
4주차/18232/18232_java_라쿤.java
4주차/21938/21938_java_라쿤.java
5주차/11582/11582_cpp_K.cpp
5주차/16432/16432_cpp_K.cpp
5주차/20922/20922_cpp_K.cpp
5주차/5107/5107_cpp_K.cpp
5주차/6198/6198_cpp_K.cpp

[케이] 5주차 과제 제출

---

4주차/16198/16198_java_라쿤.java
4주차/18232/18232_java_라쿤.java
4주차/21938/21938_java_라쿤.java
5주차/11582/11582_java_매트_v1.java
5주차/11582/11582_java_매트_v2.java
5주차/20922/20922_java_매트.java
5주차/6198/6198_java_매트.java

안녕하세여 루나, 페퍼! 매트입니다 😃
문제를 다 풀어보려 했는데 난이도가 높아서 푼 문제를 이해하고 정리하는데 에도 오랜 시간이 걸렸네요 ㅠㅜ 마니또와 moo 문제는 해결하지 못했습니다...
치킨집 문제는 두 가지 방식으로 해결해서 두 파일 모두 올려두었습니다! 또한 이번주에도 라쿤 파일은 가볍게 무시하고 리뷰해주시면 감사하겠습니다.
리뷰 잘 부탁드립니다! 감사합니다 🙏

[매트] 5주차 과제 제출

---

4주차/16198/16198_java_라쿤.java
4주차/18232/18232_java_라쿤.java
4주차/21938/21938_java_라쿤.java
5주차/20922/20299_java_아리.java
5주차/5107/5107_java_아리.java
5주차/5904/5094_java_아리.java
5주차/6198/6198_java_아리.java

안녕하세요 아리입니다~
모두가 자신의 코드를 봐주길 바라는 **관종 라쿤**의 코드는 무시해주세용~⭐️

[아리] 5주차 과제 제출

---

5주차/11582/11582_python_정.py
5주차/16432/16432_python_정.py
5주차/20922/20922_python_정.py
5주차/5107/5107_python_정.py
5주차/5904/5904_python_정.py
5주차/6198/6198_python_정.py

술 마시고 푸니까 문제가 술술 풀리지는 않네요.
그런데 시간초과가 나는 경우는 제 풀이가 틀린게 아니라 느려터진 컴퓨터의 문제가 아닐까?라는 깨달음을 얻었습니다.
감사합니다.

[정] 5주차 과제 제출

---

5주차/11582/11582_java_raccoon.java
5주차/16432/16432_java_raccoon.java
5주차/20922/20922_java_raccoon.java
5주차/5107/5107_java_raccoon.java
5주차/5904/5904_java_raccoon.java
5주차/6198/6198_java_raccoon.java

매트 연로그 반갑습니다~ 잘부탁드려요ㅎㅎ
번외로.. 많은 사람들의 커밋속에 제가 있는데.. 죄송합니다..

[라쿤] 5주차 과제 제출

---

5주차/20922/20922_java_연로그.java
5주차/5107/5107_java_연로그.java
5주차/5904/5904_java_연로그.java
5주차/6198/6198_java_연로그.java

[연로그] 5주차 과제 제출

---

4주차/16198/16198_python_제로.py
4주차/18232/18232_python_제로.py
4주차/21938/21938_python_제로.py
5주차/11582/11582_python_제로.py
5주차/11582/README.md
5주차/16432/16432_python_제로.py
5주차/16432/README.md
5주차/20922/20922_python_제로.py
5주차/20922/README.md
5주차/5107/5107_python_제로.py
5주차/5107/README.md
5주차/5904/5904_python_제로.py
5주차/5904/README.md
5주차/6198/6198_python_제로.py
5주차/6198/README.md

16432번은 pypy는 통과로 나오는데 python3에서 틀렸습니다 나오네요,,
시간초과가 아니어서 어떤 문제인지 모르겠습니다..!
잘부탁드립니다 :)

[제로] 5주차 과제 제출

---

5주차/11582/11582_python_이프.py
5주차/16432/16432_python_이프.py
5주차/20922/20922_python_이프.py
5주차/5107/5107_python_이프.py
5주차/6198/6198_python_이프.py

[이프] 5주차 과제 제출

---

5주차/11582/11582_java_포키.java
5주차/20922/20922_java_포키.java
5주차/5107/5107_java_포키.java
5주차/5904/5904_java_포키.java
5주차/6198/6198_java_포키.java

[포키] 5주차 과제 제출

---

5주차/11582/11582_python_토르.py
5주차/16432/16432_python_토르.py
5주차/20922/20922_python_토르.py
5주차/5107/5107_python_토르.py
5주차/5904/5904_python_토르.py
5주차/6198/6198_python_토르.py

안녕하세요~ 
이번꺼 조금 어려웠네요! `떡장수와 호랑이`, `Moo 게임`은 풀다가 시간을 많이 써도 못풀어서 해설을 봤네요. 문제에 제가 본 링크 남겨놨습니다. 나중에 다시 또 풀어볼 계획입니다
감사합니다!

[토르] 5주차 과제 제출

---

6주차/14938/14938_java_포키.java
6주차/24393/24393_java_포키.java

조커 찾기, 서강그라운드 두 문제 풀었습니다. 잘 부탁드립니다~!

[포키] 6주차 과제 제출

---

6주차/14938/14938_java_raccoon.java
6주차/24229/24229_java_raccoon.java
6주차/24393/24393_java_raccoon.java
6주차/25391/25391_java_raccoon.java

안녕하세요~ 다음주부터 파이썬으로 한다고 했는데.. 이번주차에 넣어버렸네요..ㅎ
자바 코드이지만..잘부탁..드려요..ㅎ

[라쿤] 6주차 과제 제출 

---

6주차/14938/14938_cpp_K.cpp
6주차/24393/24393_cpp_K.cpp
6주차/25391/25391_cpp_K.cpp

[케이] 6주차 과제 제출

---

6주차/14938/14938_java_아리.java
6주차/24393/24393_java_아리.java

이번주는 개인적으로 몸이 안좋아서 + 너무 어려워서..  두문제 밖에 못풀었네요ㅜㅠㅠㅠ
양해를 부탁드립니다,,,,

[아리] 6주차 과제 제출 

---

4주차/16198/16198_python_제로.py
4주차/18232/18232_python_제로.py
4주차/21938/21938_python_제로.py
5주차/11582/11582_python_제로.py
5주차/11582/README.md
5주차/16432/16432_python_제로.py
5주차/16432/README.md
5주차/20922/20922_python_제로.py
5주차/20922/README.md
5주차/5107/5107_python_제로.py
5주차/5107/README.md
5주차/5904/5904_python_제로.py
5주차/5904/README.md
5주차/6198/6198_python_제로.py
5주차/6198/README.md
6주차/14657/14657_python_제로.py
6주차/14657/README.md
6주차/14938/14938_python_제로.py
6주차/14938/README.md
6주차/24229/README.md
6주차/24393/README.md
6주차/25391/README.md

이번주에 본가에 내려와서 많이 못풀었네요 ㅠ
시간될때 더 풀어보겠습니다

[제로] 6주차 과제 제출

---

6주차/14938/14938_python_이프.py
6주차/24393/24393_python_이프.py
6주차/25391/25391_python_이프.py

[이프] 6주차 과제 제출

---

6주차/14938/14938_java_연로그.java
6주차/24393/24393_java_연로그.java
6주차/25391/25391_java_연로그.java

너무 어려워서 필수 두 문제만 푼 상태로 일단 제출합니다🙃
더 풀어낸 문제가 생기면 추가 push 할게요........ ㅠㅠ

[연로그] 6주차 과제 제출

---

6주차/14938/14398_python_토르.py
6주차/24229/24229_python_토르.py
6주차/24393/24393_python_토르.py
6주차/25391/25391_python_토르.py

아직 못푼 문제도 있는데 푼 문제까지 pr 제출하고 더 풀어볼게요!

[토르] 6주차 과제 제출

---

6주차/14938/14938_python_아서.py
6주차/24393/24393_python_아서.py

이번에 골드가 많네요...ㅠㅠ
어려워서 쉬운거만 풀어서 일단 제출합니다.
시간이 된다면 나머지도 도전해볼게요!

[아서] 6주차 과제제출

---

4주차/16198/16198_python_제로.py
4주차/18232/18232_python_제로.py
4주차/21938/21938_python_제로.py
5주차/11582/11582_python_제로.py
5주차/11582/README.md
5주차/16432/16432_python_제로.py
5주차/16432/README.md
5주차/20922/20922_python_제로.py
5주차/20922/README.md
5주차/5107/5107_python_제로.py
5주차/5107/README.md
5주차/5904/5904_python_제로.py
5주차/5904/README.md
5주차/6198/6198_python_제로.py
5주차/6198/README.md
6주차/14657/14657_python_제로.py
6주차/14657/README.md
6주차/14938/14938_python_제로.py
6주차/14938/README.md
6주차/24229/README.md
6주차/24393/README.md
6주차/25391/README.md
7주차/13905/README.md
7주차/16288/README.md
7주차/24499/24499_python_제로.py
7주차/24499/README.md
7주차/9694/9694_python_제로.py
7주차/9694/README.md

[제로] 7주차 문제 제출

---

5주차/5107/5107_java_렉스.java
7주차/13905/13905_java_렉스.java

[렉스] 7주차 과제 제출

---

4주차/16198/16198_java_라쿤.java
4주차/18232/18232_java_라쿤.java
4주차/21938/21938_java_라쿤.java
7주차/13905/13905_java_매트.java

이번주 프로젝트 작업량이 많아 문제에 많은 시간을 투자하지 못했네요 ㅠㅜ 리뷰 잘 부탁드립니다!

[매트] 7주차 과제 제출

---

7주차/24499/Kotlin_24499_이영환.kt

[알렉스] 7주차 과제 제출

---

7주차/24499/Ing_24499.java

[잉] 7주차 과제 제출

---

7주차/13905/13905_python_raccoon.py
7주차/16288/16288_python_raccoon.py
7주차/24499/24499_python_raccoon.py
7주차/9694/9694_python_raccoon.py

[라쿤] 7주차 과제 제출

---

7주차/24499/24499_python_이프.py

이번주차는 개인사정으로 많은 시간을 투자하지 못했습니다ㅠ

[이프] 7주차 과제 제출

---

6주차/14938/14398_python_토르.py
7주차/13905/13905_python_토르.py
7주차/16288/16228_python_토르.py
7주차/24499/24499_python_토르.py
7주차/9694/9694_python_토르.py

[토르] 7주차 과제 제출

---

7주차/13905/13905_java_연로그.java
7주차/24499/24499_java_연로그.java

[연로그] 7주차 과제 제출
